### ISSUE TITLE
Need a script for delete file & folder based on tree DFS

### ISSUE THREAD

**Issue by cnbvishal** [cnbvishal/vscode-ui#1]
I did not have time to implement delete feature.@brijesh-rohilla Can you look into it and feel free to reach out to me for any discussion and knowledge transfer related to this feature. 
 Thanks in Advanced

**Comment by brijesh-rohilla** [comment]
Hi @cnbvishal, I have some idea about what you are talking about. Can we implement this block of code:-
![Screenshot (277)](https://github.com/cnbvishal/vscode-ui/assets/66164179/dfdff29f-21ff-4676-bbc4-8e800fa17f0b)

**Comment by cnbvishal** [comment]
sure @brijesh-rohilla, create a pull request for that i will check in my system if everything will be fine then i will merge your pull request.
